coverage:
  status:
    patch:
      default:
        target: 90%
    project:
      default:
        target: auto
        threshold: 1%

ignore:
  - "cmd/ogl/**"

comment:
  layout: "diff,flags,files"
  behavior: default
  require_changes: true
